import type { NextConfig } from "next";
import { withSentryConfig } from "@sentry/nextjs";

const nextConfig: NextConfig = {
  turbopack: {
    root: process.cwd(),
  },
  // Emit browser source maps in production so `sentry-cli sourcemaps upload`
  // has real .map files to ship. Without this, Turbopack only emits minified
  // JS and Sentry stack traces stay unreadable. The postbuild upload step
  // uses --delete-after-upload to avoid serving the maps publicly.
  productionBrowserSourceMaps: true,
  // Sentry uses `onRequestError` from instrumentation; nothing extra needed.
};

/**
 * Sentry wrapper — only active in production builds on Vercel where the
 * SENTRY_AUTH_TOKEN is set (so local `next dev` stays fast and source maps
 * are not uploaded from developer machines).
 */
export default withSentryConfig(nextConfig, {
  // Project scoping — read from env, never committed.
  org: process.env.SENTRY_ORG,
  project: process.env.SENTRY_PROJECT,
  authToken: process.env.SENTRY_AUTH_TOKEN,

  // Keep CI logs clean unless we're actively debugging the plugin.
  silent: !process.env.CI,

  // Upload browser source maps AND widen to capture vendor chunks for
  // better stack traces; files are deleted from the build output afterwards
  // so they're never served publicly.
  widenClientFileUpload: true,
  sourcemaps: {
    deleteSourcemapsAfterUpload: true,
    // widenClientFileUpload scans broadly and picks up files that will never
    // have source maps, producing hundreds of "could not determine a source map
    // reference" warnings in CI logs. Ignoring them keeps the output readable
    // without affecting stack trace quality for actual application code.
    //
    // ___next_launcher.cjs  — Next.js internal function entry-point (per route)
    // **/node_modules/**    — Prisma client, import-in-the-middle (OTel), etc.
    //                         bundled into .next/node_modules; none ship .map files
    // **/*manifest.js       — build/route/chunk manifests generated by Next.js
    // required-server-files — Next.js server bootstrap, no user code inside
    ignore: [
      '**/__next_launcher.cjs',
      '**/node_modules/**',
      '**/*manifest.js',
      '**/required-server-files.js',
    ],
  },

  // Tunnel Sentry events through a Next.js route to bypass ad-blockers.
  // Keep this path generic so it isn't an obvious Sentry endpoint.
  tunnelRoute: "/monitoring",

  // Tree-shake Sentry logger statements out of the client bundle in prod.
  disableLogger: true,

  // Automatic instrumentation of Vercel Cron Monitors.
  automaticVercelMonitors: true,

  // NOTE: the Sentry plugin automatically skips source-map upload and
  // release creation when SENTRY_AUTH_TOKEN is missing (it logs a warning
  // and moves on). So local builds and previews-without-secret stay fast
  // without any extra config — runtime error capture still works.
});
